Code review 2.0
DKozl50/hash_map pull request #2
Opened 2020-03-01 21:10 UTC by DKozl50

I have finally fixed .find()!
Now it should be ready to merge.

2020-03-07 22:42 UTC, feldsherov requested changes

2020-03-07 22:42 UTC, feldsherov commented on hash_map.h
> +            this->insert(*t_begin);
не надо каждый раз писать this->

2020-03-07 22:42 UTC, feldsherov commented on hash_map.h
> +        while (t_begin != t_end) {
давай for

2020-03-07 22:42 UTC, feldsherov commented on hash_map.h
> +        }
копипаста из неконстантного метода

2020-03-07 22:42 UTC, feldsherov commented on hash_map.h
> +            return iterator(hash_table_[bucket_index].begin(), hash_table_.begin() + bucket_index, &this->hash_table_);
писал в личку про этот паттерн с длинными ифами

2020-03-07 22:42 UTC, feldsherov commented on hash_map.h
> +        else {
```
if () {
   throw ;
} else {
....
}
```

Эквивалентно

```
if () {
   throw ;
}

....


```

2020-03-10 15:09 UTC, DKozl50 commented on hash_map.h
> +        while (t_begin != t_end) {
std::for_each

2020-03-15 11:47 UTC, feldsherov requested changes

2020-03-15 11:47 UTC, feldsherov commented on hash_map.h
> +    using bucket_type = std::list<std::pair<const KeyType, ValueType>>; // = std::list<element_type>;
`using bucket_type = std::list<element_type>;`

Аналогично на строчку ниже.

2020-03-15 11:47 UTC, feldsherov commented on hash_map.h
> +    const_iterator cfind(KeyType t_key) const {
Сделать отдельный метод `c<method_name>` и потом дергать его из константного и нет метода, ок решение.

Но можно с `const_cast` поиграться https://stackoverflow.com/a/856839
и код будет жить в константном методе, а в неконтактном лезть в него используя const_cast.

2020-03-15 11:47 UTC, feldsherov commented on hash_map.h
> +    void upscale() {
try_upscale может?

2020-03-15 11:47 UTC, feldsherov commented on hash_map.h
> +        table_type new_table = table_type(4, bucket_type());
4 в константу

2020-03-15 11:47 UTC, feldsherov commented on hash_map.h
> +    void downscale() {
try_downscale

2020-03-15 11:47 UTC, feldsherov commented on hash_map.h
> +    }
У тебя вот тут куча копипасты между upscale и downscale. Давай это в функцию отправим?

2020-03-15 11:47 UTC, feldsherov commented on hash_map.h
> +        const element_type& operator*() {
Вот это можно утащить в темплейтный класс.

Возвращать [`std::conditional(condition, const element_type&, element_type&)`](https://ru.cppreference.com/w/cpp/types/conditional). 

С условием [`std::is_const<table_type >::value`](https://en.cppreference.com/w/cpp/types/is_const)

Но в readme напиши, что тебя заставляли писать на `C++11`, там в С++17 красивых вещей в этом месте завели.

2020-03-15 11:47 UTC, feldsherov commented on hash_map.h
> +        iterator(const_iterator t_iter) {
Вот эту штуку можно попробовать утащить в темплейтный класс.

Ты делаешь темплейтный конструктор по полям terator_base из которого копируешься. Дальше пишешь какую-то реализацию, которая будет работать для тебя.

2020-03-15 14:16 UTC, DKozl50 commented on hash_map.h
> +    const_iterator cfind(KeyType t_key) const {
cbegin() и cend() оставлены, так как они есть и в STL версии unordered_map ([cbegin()](https://en.cppreference.com/w/cpp/container/unordered_map/begin), [cend()](https://en.cppreference.com/w/cpp/container/unordered_map/end))

cfind() оставлен потому, что переход от const_iterator в iterator очень неудобный

2020-03-15 22:37 UTC, DKozl50 commented on hash_map.h
> +        iterator(const_iterator t_iter) {
Оставил конструкторы как есть потому, что используется трюк, имеющий смысл только на переходе с константного итератора на неконстантный.

2020-04-11 15:13 UTC, feldsherov commented on hash_map.h
> +        return const_iterator(elem_iter, hash_table_.begin() + bucket_index, &hash_table_);
Здесь и ниже, можно: std::next(it, shift); 

https://en.cppreference.com/w/cpp/iterator/next

2020-04-11 15:13 UTC, feldsherov commented on hash_map.h
> +        ++(filled_amount_);
скобочки не по делу

2020-04-11 15:13 UTC, feldsherov commented on hash_map.h
> +        for (auto &bucket: hash_table_) {
Давай вот тут нормально поитерируемся по контейнеру range based for?

2020-04-11 17:54 UTC, feldsherov approved these changes

2020-04-11 20:58 UTC, merged